AllCops:
  RunRailsCops: true
  Exclude:
    - 'Vagrantfile'
    - 'Cheffile'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'cookbooks/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false
LineLength:
  Max: 90
