language: ruby
cache: bundler
bundler_args: --without guard --deployment
rvm:
  - 2.1.0
before_script:
  - mysql -e 'create database chalmersit_test;'
  - /bin/cp $TRAVIS_BUILD_DIR/config/secrets.example.yml $TRAVIS_BUILD_DIR/config/secrets.yml
notifications:
  email: false
  irc:
    channels:
      - "irc.chalmers.it#digIT-CI"
    skip_join: true
