# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
#
# If you want to be able to access a string config[:site_title], for example:
#
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#
# 'name' is the name that appears in the edit form
#
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
#
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
#
site_title:
  name: Site Title
  type: string
  default: Informationsteknik på Chalmers
main_contact:
  name: Main Contact
  type: string
  default: styrit@chalmers.it
contact_official_name:
  name: Contact Official Name
  type: string
  default: Teknologsektionen Informationsteknik
contact_address:
  name: Contact Address
  type: string
  default: Teknologgården 2
postal_code:
  name: Postal Code
  type: string
  default: 412 58
postal_code:
  name: Postal Code
  type: string
  default: 412 58
locality:
  name: Locality
  type: string
  default: Göteborg
calendar_url:
  name: Calendar URL
  type: string
  default: "https://calendar.google.com/calendar/ical/a55ipd3o49n05cd2eebqo854qs%40group.calendar.google.com/public/basic.ics"
calendar_subscription_url:
  name: Calendar Subscription URL
  type: string
  default: "https://calendar.google.com/calendar/embed?src=a55ipd3o49n05cd2eebqo854qs@group.calendar.google.com"
